title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://actiniumn404.github.io/jekyll-test

aux_links:
  Template Repository: https://github.com/actiniumn404/jekyll-test
